### PR TITLE
Access keyserver.ubuntu.com on port 80

### PR DESCRIPTION
**Pull request by Sauraus**
This resolves https://github.com/bflad/chef-docker/issues/264

### CODE REVIEW

**Comment by Sauraus** [comment]
Those Travis errors already exist on trunk, which forked a few minutes before submitting my pull request.

**Comment by tduffield** [comment]
So I'm not super convinced that port 80 should be the default. I think it would be better to make a note in the README about this and to offer an example about how you would override this in your local environment.

**Comment by rtrauntvein** [comment]
I agree there @tduffield

**Comment by gionn** [comment]
@tduffield @rtrauntvein state reasons instead of opinions, this is a good workaround for users behind restrictive firewalls and should cause no-harm to everyone else.

**Comment by tduffield** [comment]
@Sauraus if you rebase this PR on master and Travis passes I'll merge it in. Given that Docker itself uses port 80 in it's installation procedures I no longer see a reason to enforce the default.

**Comment by Sauraus** [comment]
@tduffield rebased and recommitted.

**Pull request merged**
