### PR TITLE
Fix registry auth and slightly refactor `docker pull`

### PR DESCRIPTION
**Pull request by pstengel**
This fixes registry authentication (hopefully for good), which is still broken in 1.0.32.

When you use `Docker.authenticate!`, it sets the credentials for *all* registry API calls. This means that we can't set credentials for multiple registries upfront -- each one you set simply overrides the last. It also creates problems like we saw in #417 when credentials for a private registry are used during a call to what's supposed to be a public registry.

Instead of using `Docker.authenticate!`, we instead parse `docker_registry`'s `serveraddress` as the real `docker pull` command does and store the credentials in the node's `run_state`. We then manually verify credentials using `Docker.connection`.

We also need to refactor `docker pull` emulation:

https://github.com/BWITS/docker-api/blob/9d4ba7df1a6b52bf4d4ff1ee04c160b06939717f/README.md

According to the above link, the proper way to emulate a `docker pull` is to use `Docker::Image.create`. This call accepts a Hash containing credentials for the image creation as the second argument. It also rids of all the workarounds in place that attempted to solve #417.

### CODE REVIEW

**Comment by chasebolt** [comment]
you removed the ability to constantly pull an image and only update the resource if a new image was pulled.

```
 o = Docker::Image.get(image_identifier) if Docker::Image.exist?(image_identifier)
```

registry_host should go into a parsing function as to not duplicate code.

foodcritic threw a few errors

```
FC001: Use strings in preference to symbols to access node attributes: ./libraries/provider_docker_image.rb:80
FC001: Use strings in preference to symbols to access node attributes: ./libraries/provider_docker_registry.rb:15
FC001: Use strings in preference to symbols to access node attributes: ./libraries/provider_docker_registry.rb:24
```

**Comment by pstengel** [comment]
:+1: -- I'll commit fixes shortly

**Comment by someara** [comment]
Thanks Paul! Looking forward to this one!

-s

**Comment by pstengel** [comment]
Implemented @chasebolt's suggestions. Do you want a squash, or are the two commits okay?

**Comment by someara** [comment]
Two commits are fine. I'll take a look at this in the morning. Thanks!
-s

**Comment by someara** [comment]
I managed to get to this today!

I'm getting a converge failure right out the gate:
https://gist.github.com/someara/e93b3d20ab8d5630a606#file-gistfile1-txt-L166

You're requiring the new helper file, but never mixing in the methods...
I'd suggest namespacing it so you're not directly under DockerHelpers, then doing a

include DockerHelpers::Authentication

**Comment by pstengel** [comment]
Blah. I tested the converge before I refactored into a helper, but not after. My fault. 

I'll try to get the fix in later tonight or first thing tomorrow. 

-Paul

**Comment by someara** [comment]
no problem! this is why we have tests =)

-s

**Comment by someara** [comment]
I'm going to just go ahead and fix this up for you... one sec

**Comment by someara** [comment]
I manually fixed and squashed these as e1bbc68a90de4e8114b04e3e1e0f047e0119821f

**Comment by someara** [comment]
Releases as 1.0.33

**Comment by pstengel** [comment]
:+1:

**Pull request closed without merging**
