### PR TITLE
changing container resource to default action :run

### PR DESCRIPTION
**Pull request by chasebolt**
action run has become very stable since we switched to using the new custom resource. i think run should become the new default so containers will be redeployed on resource changes.

### CODE REVIEW

**Comment by someara** [comment]
pretty sure this is gonna require a trip through the test cookbook /
serverspecs to be mergable
-s

**Comment by someara** [comment]
er, releasable

**Comment by chasebolt** [comment]
passes test-kitchen :+1:

**Comment by chasebolt** [comment]
looking into travis-ci complaints now

**Comment by chasebolt** [comment]
all fixed up now

**Pull request merged**
