### PR TITLE
Add support for the `--log-driver` option

### PR DESCRIPTION
**Pull request by grampajoe**
This adds the `--log-driver` option to the `docker_container` resource.

As an aside, would it make sense to add something like an `extra_options` attribute to pass arbitrary options to Docker? It might help in situations where there isn't explicit support for new options like `--log-driver`.

### CODE REVIEW

**Comment by grampajoe** [comment]
It looks like the failing RuboCop check was added in a recent update, and isn't related to the changes here. Any thoughts on how to address that?

**Comment by akerekes** [comment]
+1
I also would like to use this feature.

**Comment by bkono** [comment]
I went to use the branch log-driver-support from @grampajoe and found there was a tiny problem with it (new_resources vs new_resource). Updated on my fork and pushed a pr back to fix it. Hopefully it can get merged back into this upstream after that fix.

**Comment by rtrauntvein** [comment]
+1

**Comment by habelson** [comment]
+1

**Comment by akerekes** [comment]
+1

**Comment by grampajoe** [comment]
I think this might still be held up because of unrelated failing Rubocop checks. Are there any plans to address those?

**Comment by grampajoe** [comment]
It looks like this was added in 0.40.0. I'm closing this unless that's not the case.

**Pull request closed without merging**
