### PR TITLE
Qualify port bindings with protocol even when implicitly tcp

### LINKED ISSUE #427: docker_container and port syntax
I have noticed a difference related to port bindings between the containers created with the cookbook (currently version 1.0.24) and those created with an equivalent docker client command-line.

I create my container in the cookbook like this:
```ruby
docker_container 'my-app' do
  repo 'busybox'
  tag 'ubuntu-14.04'
  port ['80', '22']
  ...
end
```

I am trying to write an assertion in my cookbook test suite to check whether the container is publishing a given port. With version 0.37 of this cookbook (which used 'docker' client command-line instead of the API), I would just search for `80/tcp` in the output of `docker inspect --format='{{ .HostConfig.PortBindings }}' for example.

However, now that the containers are created using the docker API, I can only match for `80` (without 'tcp' at the end), which means that containers created by the cookbook and by the command-line API do not docker-inspect the same anymore.

Here is a sample shell session demonstrating the problem.

```sh
# when we start, we are supposed to have converged the node and the `my-app` container exists.
root@docker-ubuntu-1404:~# docker inspect --format='{{ .HostConfig.PortBindings }}' my-app
map[22:[{ }] 80:[{ }]] # <--- new format, no '/tcp' present
root@docker-ubuntu-1404:~# docker rm -f my-app
my-app
# now I recreate the container manually using equivalent command-line
root@docker-ubuntu-1404:~# docker create --name="my-app" --publish="22" --publish="80" busybox:ubuntu-14.04 /bin/top
WARNING: Your kernel does not support swap limit capabilities, memory limited without swap.
dd7e74178fc99a23e1781028b539c2f19ba039bab17c7856309389fdbd3fe856
root@docker-ubuntu-1404:~# docker inspect --format='{{ .HostConfig.PortBindings }}'
my-app
map[22/tcp:[{ }] 80/tcp:[{ }]]  # <-- note the presence of /tcp in the output.
```

Would it be possible to change the way port bindings are created in the cookbook to follow the convention of the docker command-line client?

### PR DESCRIPTION
**Pull request by jperville**
Fixes #427.

Validated by running `kitchen test resources-182-ubuntu-1404` (no time/bandwidth to run on all supported combinations).

### CODE REVIEW

**Comment by someara** [comment]
I went to go test this, and I'm getting some errors

https://gist.github.com/someara/2066171ebcb5f3a95da5#file-gistfile1-txt-L590

-s

**Comment by someara** [comment]
^ that's on Digital Ocean with an export KITCHEN_YAML=.kitchen.cloud.yml

**Comment by jperville** [comment]
The last ones (about your sean_was_here) container are due to my changes in #437. Your test containers may be redeployed before it got a chance to reach 'running' state, it may work by adding some 'sleep' or maybe by changing the test assertion.

For the first one, it is a \n issue that I didn't spot on my only kitchen run, will try again and adjust the test if necessary (should_match will be more tolerant than eq).

**Comment by someara** [comment]
just as long as kitchen test exists zero ;)

**Comment by jperville** [comment]
Will submit separate PR in a bit.

**Comment by jperville** [comment]
PR #442 submitted, the kitchen is all green again.

**Pull request merged**
