### PR TITLE
stop/remove/run when container changed

### PR DESCRIPTION
**Pull request by dpkp**
See Issue #309 -- would love feedback on this approach.

### CODE REVIEW

**Comment by CosmicCat** [comment]
I lifted this code. It was very needed. Had problems with this line:

return true unless (!new_resource.command.nil?) && (@current_resource.command.end_with? new_resource.command)

when i removed it, things seemed to work as I wanted them to.

I also had problems regarding images without specified versions. Worked around by explicitly specifying :latest in all cases. Which is probably good practice anyway.

**Comment by dpkp** [comment]
what kind of problems did you have before removing that line? The intent there was to restart if the docker_container `command` changes.  I suspect that will be rare in most use cases, but I included for completeness.

**Comment by CosmicCat** [comment]
new_resource.command was always empty. We are not supplying explicit commands to our containers and rather use the built in default. The default command is always displayed in docker ps.

to be clearer... i suspect that this only effects cases where the :command attribute on the docker_container resource is not being set.

**Comment by CosmicCat** [comment]
which i guess means the .nil? isn't working as intended. hmm... now i am confused

**Comment by dpkp** [comment]
there's no check if @current_resource.command is nil -- that could do it

**Comment by dpkp** [comment]
failures here are rubocop style and dont apply to the code changes in this PR. would you like me to also cleanup the rubocop issues with the other code?

**Comment by wpietri** [comment]
Ooh, I'm excited to see this moving ahead. One thing I don't understand: does this detect changes in environment and volume mapping? I'm not seeing that, but I'm glad to add it either here or in a separate PR.

**Comment by someara** [comment]
Thanks for the PR.... mater has moved to talking directly to the API instead of shelling out, so this is invalid now. Closing for now.

**Pull request closed without merging**
