### PR TITLE
Fix shell_out failure

### PR DESCRIPTION
**Pull request by jhmartin**

### CODE REVIEW

**Comment by someara** [comment]
Thanks for the PR.
This should be fixed up in master. the provider now talks to the API directly instead of shelling out.

-s

**Comment by faizalzakaria** [comment]
Hi @someara , 

> provider now talks to the API directly instead of shelling out.

Does this works with Chef Solo then?

**Comment by someara** [comment]
It sure does.

**Comment by faizalzakaria** [comment]
I got shell_out missing error @someara . Chef Solo does not call the API of Chef Server what so ever. Wondering where, how this code fix the shell_out dependancy. 

As you mentioned through API, could you elaborate more?

**Comment by chasebolt** [comment]
What version of chef and this cookbook are you using?

**Comment by faizalzakaria** [comment]
12.2.1 @chasebolt  .

**Comment by chasebolt** [comment]
What cookbook version?

**Comment by faizalzakaria** [comment]
You mean the chef-docker cookbook ? 2.1.2 (tip of master branch).

**Comment by faizalzakaria** [comment]
Now I get it. Thanks @chasebolt @someara .

**Pull request closed without merging**
